// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAISBUzqrnqNxvO9tjj3nR5TTjvDlKUkE',
    appId: '1:226827460415:web:56f72c5b8cd6c33a1b7d8a',
    messagingSenderId: '226827460415',
    projectId: 'jkt-scapade',
    authDomain: 'jkt-scapade.firebaseapp.com',
    storageBucket: 'jkt-scapade.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZOiaU3cn36lre_cJrDJ_AdGNTvWjJXA',
    appId: '1:226827460415:android:84a95b3870e8db121b7d8a',
    messagingSenderId: '226827460415',
    projectId: 'jkt-scapade',
    storageBucket: 'jkt-scapade.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAISBUzqrnqNxvO9tjj3nR5TTjvDlKUkE',
    appId: '1:226827460415:web:375f3011c3fa49381b7d8a',
    messagingSenderId: '226827460415',
    projectId: 'jkt-scapade',
    authDomain: 'jkt-scapade.firebaseapp.com',
    storageBucket: 'jkt-scapade.firebasestorage.app',
  );
}
